git:
  # required, the git repository from where to download Kubernetes object files
  url: "git@github.com:autoapply/template-kubectl.git"
  # optional, the path within the repository
  path:
    - "."
secrets:
  # optional, the SSH key used to access the repository, can be generated
  # using "ssh-keygen" (please check the correct indentation here!)
  ssh: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIJKQIBAAKCAgEA0tI0gtK7uc60kiQ1RcVAcg2r896uXZR5qWAPZbC53g5iwqwb
    VqRydbSMzuOlSXu7EL2h...
    -----END RSA PRIVATE KEY-----
  # optional, the credentials that will be used to access the Docker registry
  dockercfg: ""
  # optional, the yaml-crypt keys to decrypt secret files in the repository
  # see https://github.com/autoapply/yaml-crypt for more information
  yaml-crypt:
    - ""
  # optional, the parameters that should be passed to sops
  # see https://github.com/mozilla/sops#usage for more information
  # on which environment variables are required for decryption
  sops:
    SOPS_PGP_FP: "28A4E3742FF30047277C32E266C52CA05F3FB2E4"
  # optional, the GPG keys to import
  gpg: |
    -----BEGIN PGP PRIVATE KEY BLOCK-----
    
    lQOXBF0XaMUBCADOE9jWQ7PwwT+Dlb6SnRsaff9FkAusFORfpqWSS2DCkxJPZLOK
    dfM5RAqVCLq+O2N...
    -----END PGP PRIVATE KEY BLOCK-----
  others:
    SOME_OTHER_SECRET: "secret123"
kubernetes:
  # optional, the namespace where the autoapply objects will be created
  namespace: "autoapply"
  # optional, whether to run "kubectl kustomize", see
  # https://kubernetes.io/docs/tasks/manage-kubernetes-objects/kustomization/
  kustomize: false
